openapi: 3.0.3
info:
  title: API Gestion Utilisateurs
  description: API pour récupérer des utilisateurs avec pagination
  version: 1.0.0

paths:
  /users:
    get:
      summary: Récupérer la liste des utilisateurs
      description: Retourne une liste d'utilisateurs avec pagination
      parameters:
        - name: page
          in: query
          description: Numéro de la page (défaut 1)
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: size
          in: query
          description: Nombre d'éléments par page (défaut 20)
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
      responses:
        '200':
          description: Liste des utilisateurs récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: Ny Anja
                    email:
                      type: string
                      format: email
                      example: nyanja@example.com
        '400':
          description: Mauvais paramètres fournis
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Bad types for provided query parameters"