openapi: 3.0.3
info:
  title: API Recherche de Produits
  description: API pour rechercher et filtrer des produits
  version: 1.0.0

components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
          example: "Pommes Bio"
        expiration_datetime:
          type: string
          format: date-time
          example: "2024-12-31T23:59:59Z"
        price:
          type: number
          format: decimal
          example: 3.50
      required:
        - name
        - expiration_datetime
        - price

  parameters:
    LimitParam:
      name: limit
      in: query
      description: Nombre maximum d'éléments à retourner
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 10
      example: 20

    QueryParam:
      name: q
      in: query
      description: Terme de recherche pour filtrer les produits
      required: false
      schema:
        type: string
        minLength: 1
      example: "pomme"

paths:
  /products:
    get:
      summary: Rechercher des produits
      description: Retourne une liste de produits filtrés selon les critères
      parameters:
        - $ref: '#/components/parameters/LimitParam'
        - $ref: '#/components/parameters/QueryParam'
      responses:
        '200':
          description: Liste des produits trouvés
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              examples:
                multiple_products:
                  summary: Résultat avec plusieurs produits
                  value:
                    - name: "Pommes Bio"
                      expiration_datetime: "2024-12-31T23:59:59Z"
                      price: 3.50
                    - name: "Pommes de terre"
                      expiration_datetime: "2025-01-15T12:00:00Z"
                      price: 2.80
                    - name: "Jus de pomme"
                      expiration_datetime: "2024-11-20T10:30:00Z"
                      price: 4.20

                empty_result:
                  summary: Aucun produit trouvé
                  value: []